import 'package:flutter/material.dart';
import '../../events/presentation/record_event_sheet.dart';
class HomeScreen extends StatelessWidget { const HomeScreen({super.key});
  @override Widget build(context)=>Scaffold(appBar:AppBar(title:const Text('Good evening'),actions:const [Padding(padding:EdgeInsets.all(16),child:Chip(avatar:Icon(Icons.cloud_done,size:16),label:Text('Synced')))]),body:ListView(padding:const EdgeInsets.all(16),children:[
    Text('What’s happening right now?',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:16),
    LayoutBuilder(builder:(context,c)=>Wrap(spacing:16,runSpacing:16,children:[_BabyCard(name:'Baby A',width:c.maxWidth>650?(c.maxWidth-16)/2:c.maxWidth,sleeping:false),_BabyCard(name:'Baby B',width:c.maxWidth>650?(c.maxWidth-16)/2:c.maxWidth,sleeping:true)])),const SizedBox(height:100)])); }
class _BabyCard extends StatelessWidget { const _BabyCard({required this.name,required this.width,required this.sleeping});final String name;final double width;final bool sleeping;
  @override Widget build(context)=>SizedBox(width:width,child:Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[CircleAvatar(child:Text(name.substring(name.length-1))),const SizedBox(width:12),Text(name,style:Theme.of(context).textTheme.titleLarge)]),const SizedBox(height:20),const _Status(Icons.local_drink_outlined,'Last feed','1h 20m ago · 90 ml'),_Status(Icons.bedtime_outlined,'Sleep',sleeping?'Sleeping for 42m':'Awake for 35m'),const _Status(Icons.baby_changing_station,'Last nappy','2h 10m ago'),const Divider(height:28),Wrap(spacing:8,runSpacing:8,children:['Feed',sleeping?'Wake up':'Start sleep','Nappy'].map((x)=>FilledButton.tonal(onPressed:()=>showModalBottomSheet(context:context,showDragHandle:true,builder:(_)=>const RecordEventSheet()),child:Text(x))).toList())])))); }
class _Status extends StatelessWidget {const _Status(this.icon,this.title,this.value);final IconData icon;final String title,value;@override Widget build(context)=>ListTile(contentPadding:EdgeInsets.zero,leading:Icon(icon),title:Text(title),subtitle:Text(value),dense:true);}
